services: # TODO: add poller
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - lp_tracker_network

  commands_listener:
    build:
      context: .
      dockerfile: docker/Dockerfile.commands_listener
    container_name: commands_listener
    restart: unless-stopped
    environment:
      - DOCKER_ENV=true
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - RIOT_API_KEY=${RIOT_API_KEY}
      - MONGO_URI=${MONGO_DOCKER_URI}
    depends_on:
      - mongodb
    networks:
      - lp_tracker_network

volumes:
  mongodb_data:
  mongodb_config:

networks:
  lp_tracker_network: